# Folosind imaginea NGINX ce este disponibila pe docker hub
FROM nginx:latest

# Copiem fisierul nostru index.html in folderul /usr/share/nginx/html
COPY ./index.html /usr/share/nginx/html/index.html
